apiVersion: v1
kind: Service
metadata:
  name: ci-node-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ci-node-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
